---
# tasks file for avinetworks.avicontroller_gke

# - name: Avi Controller | GKE | Resume deplyoment | set replicas to 1
#   k8s_scale:
#     api_version: v1
#     kind: StatefulSet
#     name: node-0
#     namespace: "{{ avi_namespace }}"
#     replicas: 1
#     wait_timeout: 60

- name: Avi Controller | GKE | Resume deplyoment | set replicas to 1
  command: kubectl scale -n {{ avi_namespace }} --replicas=1 statefulset/node-0
